### ISSUE TITLE
TypeError: _.pluralize is not a function

### ISSUE THREAD

**Issue by igorbezsmertnyi** [commercelayer/commercelayer-js-sdk#11]
I have the next problem in my React project

Log:

```
TypeError: _.pluralize is not a function
ResourceLibrary.value
node_modules/active-resource/dist/active-resource.min.js:8
```

<img width="1016" alt="Screenshot 2020-03-26 at 8 31 39 AM" src="https://user-images.githubusercontent.com/21984930/77621196-4421ad00-6f3c-11ea-9592-b005c9721189.png">

Stack:
```
node: 10.15.3
npm: 6.4.1
```

**Comment by acasazza** [comment]
Hi @igorbezsmertnyi,

Can you give me some information? What are you trying to do?

Thank you!

**Comment by Nexum** [comment]
He was trying to run this in node.js, i have the same problem... sadly the issue seems to be active-resource :(

**Comment by Nexum** [comment]
Ok after further investigation the issue seems to be related to projects using underscore themselves... 
`
const _ = require("underscore");
var test = require("@commercelayer/js-sdk");
`
this is enough to break it :(
