### ISSUE TITLE
Unable to update some order properties

### ISSUE THREAD

**Issue by zaracooper** [commercelayer/commercelayer-js-sdk#33]
According to the[ Commerce Layer Guide](https://docs.commercelayer.io/guides/) in the [Adding a billing address section](https://docs.commercelayer.io/guides/checkout/adding-a-billing-address), you should be able to update the `_billing_address_clone_id` and `_shipping_address_same_as_billing` attributes of an order. However, when attempting this with the sdk, they do not seem to get updated. 

Here's the code I'm using:
```javascript
const order = await Order.find('orderId');
await order.update({
    _billingAddressCloneId: 'addressId',
   _shippingAddressSameAsBilling: 1 
   // official documentation lists _shippingAddressSameAsBilling as a boolean value 
   // but the sdk lists it as a number, so 1 = true, 0 = false is my assumption.
   // setting it as a 0 or 1 value throws errors, I'm not sure why this happens
})
```
When attempting to set them, both are `null`.
Can these fields be set?

**Comment by acasazza** [comment]
Hi @zaracooper, what version are you using?
Btw, Did you try to pass `boolean` as `_shippingAddressSameAsBilling `?

**Comment by zaracooper** [comment]
Thanks for the reply @acasazza . Yes. That was the first thing I did because I was going off of the official documentation. But I still go an error. I'm using version `3.5.0`.

**Comment by acasazza** [comment]
You're welcome. So, could you try to upgrade to `v3.6.1`, please?

**Comment by zaracooper** [comment]
Will do. Thanks, @acasazza .

**Comment by zaracooper** [comment]
@acasazza unfortunately upgrading to `v3.6.1` didn't fix the issue. Both `_billingAddressCloneId` and `_shippingAddressSameAsBilling` fields of an order are not updateable using the SDK.

**Comment by zaracooper** [comment]
I'm finding a similar issue with the `paymentMethod` field:

```javascript
    const paymentMethod = await PaymentMethod.find('paymentMethodId');

    order = await order.update({ paymentMethod: paymentMethod });
```
`paymentMethod` comes up `null` on subsequent of an updated order. Using `v3.6.1` of the SDK.

**Comment by acasazza** [comment]
@zaracooper, Are you sure? Because I did several tests and everything works properly, our `react-components` uses the SDK to update the order with those attributes. Is it possible that you are using the wrong `addressId`?

**Comment by zaracooper** [comment]
I'm certain the address Id is valid. The [guide](https://docs.commercelayer.io/guides/checkout/adding-a-billing-address#example-1) requires that customer addresses are fetched first (with addresses included), then an address taken from a selected customer address. 

Whenever I update `paymentMethod`, `_billingAddressCloneId` and `_shippingAddressSameAsBilling` fields, the update itself does not throw an error. The problem is when I fetch the order, the updates seem not to have been applied to the fields mentioned.

**Comment by acasazza** [comment]
@zaracooper, I gotcha your issue. If you reload the order twice, you will get the updates. But it's not an SDK problem, so you can resolve this issue by putting  `_shippingAddressCloneId ` instead of `_shippingAddressSameAsBilling` with the same `addressId`.

Let me know if it works.
