### ISSUE TITLE
Cannot update Address line1/line2 attributes

### ISSUE THREAD

**Issue by andonimihai** [commercelayer/commercelayer-js-sdk#36]
Hi.
It seems like i cannot update address line1 and line2 attributes. Bellow is the code i use. As you see, the attributes are different from the one i read data(`line1` and `line2`). If i try to use the name without underscore, then i receive this error:

```json
{
  "errors": [
    {
      "title": "Param not allowed",
      "detail": "line1 is not allowed.",
      "code": "PARAM_NOT_ALLOWED",
      "status": "400"
    }
  ]
}
```

Can you help me figure out how to properly update these address details?

**CODE**

```typescript
const persistedAddress = await Address.withCredentials({
    accessToken,
    endpoint,
  }).find(address.id);

  await persistedAddress.withCredentials({ accessToken, endpoint }).update({
    line_1: address.addressLine1,
    line_2: address.addressLine2,
  });

```

**Comment by acasazza** [comment]
Fixed by `v4.1.3`
