### ISSUE TITLE
Question about returned items from sdk/api

### ISSUE THREAD

**Issue by redmagic** [commercelayer/commercelayer-js-sdk#38]
Hi,

I am deciding on how to use the api, with this sdk or with the regular REST calls?
In my opinion, the REST has better documentation, but the sdk seems more developer friendly.
The responses seem to be a bit different.

For example, I am getting a CollectionResponse from `CLayer.Sku.all()`, which is fine.
I am trying get a response in the same format as calling `https://${domain}/api/skus`, is this possible? Or should I forget about that and use the sdk output, together with `CollectionResponse.toArray()` for example?

The documentation of CollectionResponse is a bit lacking there, IMHO.

**Comment by acasazza** [comment]
Hi @redmagic,

Yes, there is a way to figure out your question. Just adding `{ rawResponse: true }` to `all` method.
It will return a native object like a REST call.
It's a new feature and we're writing the documentation, it will be out more or less in 3 days. 

You can take a look at these tests 😉 https://github.com/commercelayer/commercelayer-js-sdk/blob/master/specs/rawResponse.spec.ts

> Remember one thing, if you're using `rawResponse`, you will be not able to use Collection methods on the response.

**Comment by redmagic** [comment]
Hi Alessandro,

Thanks, I will look into that!
