### ISSUE TITLE
Documentation - list & describe all available methods

### ISSUE THREAD

**Issue by westhouseit** [commercelayer/commercelayer-js-sdk#40]
I can see quite a few methods are already listed in the README, but is there somewhere to find all of them without going through the code? Perhaps something like the API documentation?

**Comment by westhouseit** [comment]
As an update, if you build via the OpenAPI schema it will generate this for you.

**Comment by acasazza** [comment]
The new version is based on the OpenAPI schema. You can find more looking at `active-resource` documentation, here https://github.com/nicklandgrebe/active-resource.js/blob/master/README.md.
