### ISSUE TITLE
Open development

### ISSUE THREAD

**Issue by westhouseit** [commercelayer/commercelayer-js-sdk#41]
Hey guys. I know you're working on an updated JS SDK, but it's hard to make project decisions without some idea of progress and timescales. Is there any chance you could make the development public or perhaps use the Github Wiki milestones or similar?

**Comment by acasazza** [comment]
Hey there. The new SDK will release next month. If you are in hurry, you can use the current version without problems.

**Comment by westhouseit** [comment]
Thanks for putting the beta version up for initial testing!
