### ISSUE TITLE
Active Resource error: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by citlacom** [commercelayer/commercelayer-js-sdk#45]
When trying to run an SDK query to get the customerGroup that is associated to a market there is an error on markets that don't have associated a customer group. Here is the error trace:

```
gstCustomer group resolution failed for market Pablo's Test: TypeError: Cannot read property 'data' of undefined
    at /Users/pablocc/Sites/therefore/trudmw-web-gat/node_modules/@commercelayer/active-resource/dist/active-resource.js:1347:75
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at extractProperties (/Users/pablocc/Sites/therefore/trudmw-web-gat/commands/src/commands/clexport.js:148:43)
    at async Promise.all (index 4)
    at ExportCommerceLayerData.getMarketsData (/Users/pablocc/Sites/therefore/trudmw-web-gat/commands/src/commands/clexport.js:174:23)
    at /Users/pablocc/Sites/therefore/trudmw-web-gat/commands/src/commands/clexport.js:76:31
```

The API call is very simple:

I have a MarketCollection object and I perform the following query:

  ```
const customerGroupCollection = await market
    .customerGroup()
    .load()
```

On the markets that have a customer group reference the error is not happening but in the one that is empty you get the described error.

I tried to avoid calling load() method validating if the reference is empty, but the empty method always returns "true" even when some of the markets has a referenced customer group. Here what I tried:

```
  if (!market.customerGroup().empty()) {
    const customerGroupCollection = await market
      .customerGroup()
      .load()

    const myMarketData = extend(marketData, {
      segment: customerGroupCollection.first().name
    })
  }
```

For the markets where I have associated customer groups the empty check is indicating that there is no referenced customerGroup and the condition never pass so cannot extract the Customer Group name. I was not able to find any examples of how to deal accessing the customer group collection referenced entity at your specs tests: https://github.com/commercelayer/commercelayer-js-sdk/tree/master/specs

This use case is not covered in your specs so apparently this looks like a bug. 

Can you validate if I'm doing anything wrong that is causing this error or if this is a bug? Thanks!

**Comment by acasazza** [comment]
Hello @citlacom, please, could you use our new SDK https://github.com/commercelayer/commercelayer-sdk? this library will be deprecated in a few next days. Thank you!
